# Generated by Django 4.2.1 on 2023-05-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0003_rename_left_right_node_left_node_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='left',
        ),
        migrations.RemoveField(
            model_name='node',
            name='right',
        ),
    ]
